name: unity build plugins (custom backend)

on: 
  workflow_dispatch:
    inputs:
      backend:
        description: 'js backend'     
        required: true
      config:
        type: choice
        description: Release Or Debug
        options:
        - Release
        - Debug

env:
  RUNID: 613573412

jobs:
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: ${{ github.event.inputs.backend }}
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r21b-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
      - name: Build
        run: |
          cd unity/native_src
          ANDROID_NDK=~/android-ndk-r21b node make.js --platform android --backend ${{ github.event.inputs.backend }} --config ${{ github.event.inputs.config }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins (${{ github.event.inputs.backend }}_${{ github.event.inputs.config }})
  ios:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: ${{ github.event.inputs.backend }}
      - name: Use Xcode 12.0 for x86
        run: sudo xcode-select -switch "/Applications/Xcode_12.app"
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform ios --backend ${{ github.event.inputs.backend }} --config ${{ github.event.inputs.config }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins (${{ github.event.inputs.backend }}_${{ github.event.inputs.config }})
  osx:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: ${{ github.event.inputs.backend }}
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform osx --backend ${{ github.event.inputs.backend }} --config ${{ github.event.inputs.config }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins (${{ github.event.inputs.backend }}_${{ github.event.inputs.config }})
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: ${{ github.event.inputs.backend }}
      - name: Build
        run: |
          cd unity\native_src
          node make.js --platform win --backend ${{ github.event.inputs.backend }} --config ${{ github.event.inputs.config }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins (${{ github.event.inputs.backend }}_${{ github.event.inputs.config }})
  linux64:
    runs-on: ubuntu-latest

    steps:
      - name: Install libc++-dev
        run: |
          sudo apt-get install clang
          sudo apt-get install libc++-dev
          sudo apt-get install libc++abi-dev
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: ${{ github.event.inputs.backend }}
      - name: Build
        run: |
          cd unity/native_src
          node make.js --platform linux --backend ${{ github.event.inputs.backend }} --config ${{ github.event.inputs.config }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins (${{ github.event.inputs.backend }}_${{ github.event.inputs.config }})
 